add_subdirectory(libs)
add_subdirectory(libs/pybind11)
add_subdirectory(libs/imgui)
add_subdirectory(python)
add_subdirectory(testCodes)
add_subdirectory(renderTech)
add_subdirectory(products/baseApp)
add_subdirectory(apps)
add_subdirectory(products/faceDetector)
#if(NOT IS_MACOS)
#add_subdirectory(embreeScene)
#add_subdirectory(render)
#endif()
#if(IS_WINDOWS)
#add_subdirectory(physics)
#endif()